[package]
name = "rust_epoll_coroutines_by_nix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.24.1"
futures = "0.3.21"
lazy_static = "1.4.0"